apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-app
  template:
    metadata:
      labels:
        app: sql-app
    spec:
      containers:
      - name: sql-app
        image: mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: my-sql-credentials # Reference the secret name
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
