apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
  - ReadWriteOnce # Or ReadWriteMany for multi-pod access
  resources:
    requests:
      storage: 10Gi # Adjust storage size as needed
  storageClassName: local-storage # Leave empty for default storage class
