apiVersion: v1
kind: Secret
metadata:
  name: my-sql-credentials # Replace with your desired secret name
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "example"
  MYSQL_DATABASE: "Laptop"
  MYSQL_USER: "eden"
  MYSQL_PASSWORD: "eden"

