apiVersion: v1
kind: Pod
metadata:
  name: my-linux-pod
spec:
  containers:
  - image: ubuntu
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: busy-box
  restartPolicy: Always
