apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs # Match labels with your Node.js Deployment
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the service
    targetPort: 8000 # Port your Node.js app listens on inside the container
    nodePort: 31000 # Explicitly assign NodePort 31000 for external access
  type: NodePort # Change to NodePort or LoadBalancer if needed
